#include<stdio.h>
int main()
{
    int year,month,day;
    while(~scanf("%d %d",&year,&month))
    if(year%400==0||year%4==0&&year%100!=0)
    {
        {if(month==1){
                printf("31",&day);}}
        {if(month==2){
                printf("29",&day);}}
        {if(month==3){
                printf("31",&day);}}
        {if(month==4){
                printf("30",&day);}}
        {if(month==5){
                printf("31",&day);}}
        {if(month==6){
                printf("30",&day);}}
        {if(month==7){
                printf("31",&day);}}
        {if(month==8){
                printf("31",&day);}}
        {if(month==9){
                printf("30",&day);}}
        {if(month==10){
                printf("31",&day);}}
        {if(month==11){
                printf("30",&day);}}
        {if(month==12){
                printf("31",&day);}}
        puts("\0");
        }
    else
    {
        {if(month==1){
                printf("31",&day);}}
        {if(month==2){
                printf("28",&day);}}
        {if(month==3){
                printf("31",&day);}}
        {if(month==4){
                printf("30",&day);}}
        {if(month==5){
                printf("31",&day);}}
        {if(month==6){
                printf("30",&day);}}
        {if(month==7){
                printf("31",&day);}}
        {if(month==8){
                printf("31",&day);}}
        {if(month==9){
                printf("30",&day);}}
        {if(month==10){
                printf("31",&day);}}
        {if(month==11){
                printf("30",&day);}}
        {if(month==12){
                printf("31",&day);}}
        puts("\0");
        }
    return 0;
}